version: '3.8'

services:
  mcp-storage:
    build: .
    container_name: mcp-storage-go
    ports:
      - "5475:5435"
    env_file:
      - .env.docker
    environment:
      - PORT=5435
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    restart: unless-stopped
