version: '3.8'

services:
  mcp-storage:
    build: .
    container_name: mcp-storage-go
    ports:
      - "5435:5435"
    env_file:
      - .env
    environment:
      - PORT=5435
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge