version: '3.8'

services:
  mcp-storage:
    build: .
    container_name: mcp-storage-server
    ports:
      - "5435:5435"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge